export const ADD_TO_SHOPPINGBAG = 'ADD_TO_SHOPPINGBAG'
export const ADD_TO_WISHLIST = 'ADD_TO_WISHLIST'
export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS'
export const REMOVE_FROM_BAG = 'REMOVE_FROM_BAG'
export const SELECTED_SIZE = 'SELECTED_SIZE'


export const userConstants = {
    REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
    REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
    REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',
 
    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',
 
    LOGOUT: 'USERS_LOGOUT',
}