export const ADD_TO_SHOPPINGBAG = 'ADD_TO_SHOPPINGBAG'
export const ADD_TO_WISHLIST = 'ADD_TO_WISHLIST'
export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS'
export const REMOVE_FROM_BAG = 'REMOVE_FROM_BAG'
export const SELECTED_SIZE = 'SELECTED_SIZE'

export const UPDATE_INVENTORY = 'UPDATE_INVENTORY'
export const ADD_TO_BAG_FAILURE = 'ADD_TO_BAG_FAILURE'

export const USER_LOGGED_IN = 'USER_LOGGED_IN'
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT'


export const CHECKOUT_REQUEST = 'CHECKOUT_REQUEST'
export const CHECKOUT_SUCCESS = 'CHECKOUT_SUCCESS'
export const CHECKOUT_FAILURE = 'CHECKOUT_FAILURE'
