export const ADD_TO_SHOPPINGBAG = 'ADD_TO_SHOPPINGBAG'
export const ADD_TO_WISHLIST = 'ADD_TO_WISHLIST'
export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS'
export const REMOVE_FROM_BAG = 'REMOVE_FROM_BAG'

